apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil
  namespace: dev
  labels:
    app: wil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
        - name: wil
          image: wil42/playground:v2
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-service
spec:
  selector:
    app: wil
  type: NodePort
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30036
      protocol: TCP
